FROM clojupyter-base:0.3.2
LABEL maintainer="Klaus Harbo <klaus@harbo.net>"

ARG NB_USER=jovyan

ENV NOTEBOOK_PATH $HOME/notebooks
ENV PORT 8888
ENV LEIN_ROOT 1
ENV CLOJUPYTER_PATH $HOME/clojupyter

USER $NB_USER
RUN	mkdir -p $NOTEBOOK_PATH \
    && git clone https://github.com/clojupyter/clojupyter $CLOJUPYTER_PATH

WORKDIR $CLOJUPYTER_PATH
ARG CLOJUPYTER_VERSION
RUN echo $CLOJUPYTER_VERSION
RUN git checkout $CLOJUPYTER_VERSION \
    && make install

WORKDIR $NOTEBOOK_PATH
EXPOSE $PORT
VOLUME $NOTEBOOK_PATH
CMD ["jupyter", "notebook", "--log-level=ERROR"]
