name: Deploy to Docker
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Monorepo Publish
              uses: ivyxjc/docker-monorepo-action@master
              with:
                  token: ${{ secrets.GIT_TOKEN}}
