name: multi-docker-build-push

on:
    push:
        branches: master

jobs:
    multi:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: install python dependencies [requests]
              run: |
                  python -m pip install --upgrade pip
                  pip install requests pytz
            - name: download docker python
              run: |
                  wget https://gist.githubusercontent.com/ivyxjc/8bf4c09745fa4429ae96b7b892df3252/raw/actions-docker.py
            - name: docker logout
              run: |
                  docker logout
            - name: run docker python
              run: |
                  echo ${{secrets.DOCKERHUB_TOKEN}} | docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password-stdin \
                  && python ./actions-docker.py
